# planet.js configuration

planet:
  name: "neoFelhz's Planet" # Site title
  tagline: "neoFelhz 的伙伴星球" # Site tagline
  description: "neoFelhz 的伙伴星球" # Site description
  link: https://planet.nfz.moe # Site link, do NOT include tailing slash '/'
  locale: zh-CN # Site locale
  owner_name: neoFelhz # Your name
  owner_email: neoFelhz@gmail.com # Your email
  theme: mdui # theme under templates directory
  output: public # output directory, make sure your web server can read in this place
  timeout: 40 # request timeout in seconds
  items: 150 # how many posts should be displayed?
  items_feed: 300 # maximum posts in feed
  display_length: 700 # posts longer than this characters, a summary will be displayed (if available)
  time_format: YYYY MMMM Do h:mm:ss A # See http://momentjs.com/docs/#/displaying/ for details
  ttl: 120 # TimeToLive minutes to cache site feed
  lazyload: true # Use Lazyload for image
  		  
secure:
  proxy: # Leave blank if you don't use an http proxy
  allowedTags: # set to true to allow any tags, or [] to disallow any.
  - h1
  - h2
  - h3
  - h4
  - h5
  - h6
  - blockquote
  - p
  - a
  - ul
  - ol
  - nl
  - li
  - b
  - i
  - s
  - g
  - strong
  - em
  - strike
  - del
  - pre
  - code
  - kbd
  - hr
  - br
  - div
  - table
  - thead
  - tbody
  - tr
  - th
  - td
  - caption
  - img
  - sup
  - sub
  - span
  - font
  - style
  - svg
  - defs
  - path
  - use
  - [script]
  allowedAttributes:
    a:
    - href
    - name
    - target
    img:
    - src
  selfClosing:
  - img
  - br
  - hr
  allowedSchemes:
  - http
  - https
  - ftp
  - mailto
  allowProtocolRelative: true

people:
- name: neoFelhz
  link: https://blog.nfz.moe/atom.xml
  avatar: https://bbs-static.nfz.yecdn.com/avatar/avatar.png
- name: SkyEdge
  link: https://liyin.date/rss2.xml
  avatar: https://bbs-static.nfz.yecdn.com/links/liyin.date.png
- name: Viosey
  link: https://blog.viosey.com/atom.xml
  avatar: https://bbs-static.nfz.yecdn.com/links/viosey.com.png
- name: 蠢黑通行
  link: https://blackyau.cc/feed
  avatar: https://bbs-static.nfz.yecdn.com/links/blackyau.cc.jpg
- name: Zohar
  link: https://www.iwch.me/feed
  avatar: https://bbs-static.nfz.yecdn.com/links/www.iwch.me.jpg
- name: KookXiang
  link: https://ikk.me/feed
  avatar: https://bbs-static.nfz.yecdn.com/links/ikk.me.jpg
- name: LWL12
  link: https://blog.lwl12.com/feed
  avatar: https://bbs-static.nfz.yecdn.com/links/blog.lwl12.com.jpg
- name: 萨摩公园
  link: https://i-meto.com/rss/
  avatar: https://bbs-static.nfz.yecdn.com/links/i-meto.com.jpg
- name: Troy
  link: https://itroy.cc/feed
  avatar: https://bbs-static.nfz.yecdn.com/links/itroy.cc.png
- name: KeJun
  link: https://blog.kejun.space/feed.xml
  avatar: https://bbs-static.nfz.yecdn.com/links/kejun.space.png
- name: mokeyjay
  link: https://www.mokeyjay.com/feed
  avatar: https://bbs-static.nfz.yecdn.com/links/www.mokeyjay.com.jpg
- name: Halyul
  link: https://blog.halyul.cc/atom.xml
  avatar: https://bbs-static.nfz.yecdn.com/links/halyul.com.png
- name: Axton
  link: https://flyhigher.top/feed
  avatar: https://bbs-static.nfz.yecdn.com/links/flyhigher.top.png
- name: PoiScript
  link: https://blog.poi.cat/atom.xml
  avatar: https://bbs-static.nfz.yecdn.com/links/blog.poi.cat.png
- name: DCC
  link: https://dcc.cat/feed
  avatar: https://bbs-static.nfz.yecdn.com/links/dcc.cat.png
- name: Netrvin
  link: https://131.re/feed
  avatar: https://bbs-static.nfz.yecdn.com/links/131.re.jpg
- name: Ice-Hazymoon
  link: https://imiku.me/feed
  avatar: https://bbs-static.nfz.yecdn.com/links/imiku.me.png
- name: 只有一秒的记忆
  link: https://blog.asec01.net/feed.xml
  avatar: https://bbs-static.nfz.yecdn.com/links/blog.asec01.net.png
- name: Lirici
  link: https://blog.lirici.moe/feed
  avatar: https://bbs-static.nfz.yecdn.com/links/lirici.moe.jpg
- name: Milkice
  link: https://milkice.me/feed/
  avatar: https://bbs-static.nfz.yecdn.com/links/milkice.me.jpg
- name: Ephen
  link: https://ephen.me/atom.xml
  avatar: https://bbs-static.nfz.yecdn.com/links/ephen.me.jpg
- name: 可乐没气的猫
  link: https://www.isthnew.com/atom.xml
  avatar: https://bbs-static.nfz.yecdn.com/links/www.isthnew.com.png
- name: Maekawa_Miku
  link: https://1111lab.org/?feed=rss2
  avatar: https://sfs.1111lab.org/1111Lab/Avatar.jpg
